apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-deployment
  labels:
    app: pokemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon
  template:
    metadata:
      labels:
        app: pokemon
    spec:
      containers:
      - name: pokemon
        image: pokemon-service:latest
        env:
          - name: CONFIG_MAP
            valueFrom:
              configMapKeyRef:
                name: pokemon-config
                key: config.map
        imagePullPolicy: Never
        ports:
          - containerPort: 8080