apiVersion: v1
kind: Service
metadata: 
  name: pokemon-service-nodeport

# Note: Using NodePort you should open the sg of the node in order to access to it on the specified port
spec:
  type: NodePort
  selector: 
    app: pokemon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
