  apiVersion: v1
  kind: Service
  metadata:
    name: pokemon-service
  spec:
    type: LoadBalancer
    selector:
      run: pokemon-pod
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
